language: node_js
node_js:
   - "4.1"

branches:
  only:
    - master
    - dev

after_success:
  make test-coveralls

before_install:
  npm install babel jade coffee-script

notifications:
    email: false
